twig:
    default_path: '%kernel.project_dir%/templates'

    # la propriété form_themes permet de choisir le modèle de construction des formulaires html
    form_themes: ["bootstrap_4_layout.html.twig"]

    # la propriété 'globals' permet de créer des variables globales (⚠ la valeur ne peut être variable)
    globals:
        chemin_images: "/img/"
        chemin_couvertures: "/img/couvertures/"
    
    # la propriété 'date' va permettre de configurer le format par défaut d'affichage des date
    date:
        format: d/m/Y
